export class Bond{
	idCreator:{
		id:number;
	}
    vNominal:number;
	vComercial:number;
	nYears:number;
	dxp:number;
	dxa:number;
	impRenta:number;
	tea:number;
	tDes:number;
	pCavali:number;
	pCol:number;
	pEstruct:number;
	pFlot:number;
	pPrima:number;
	method:string;
	estado:boolean;
	typeMoney:string;
}